# Generated by Django 4.2.2 on 2023-08-20 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namn', models.CharField(max_length=255)),
                ('latin', models.CharField(max_length=255)),
                ('info', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='insamlingsperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_namn', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namn', models.CharField(max_length=255)),
                ('info', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='landskap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namn', models.CharField(max_length=255)),
                ('info', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='odlingsmaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ursprungskalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=255)),
                ('lan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.lan')),
                ('landskap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.landskap')),
            ],
        ),
        migrations.CreateModel(
            name='planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pvn', models.CharField(default=0, max_length=6)),
                ('diskriminator', models.IntegerField()),
                ('rotade', models.CharField(max_length=255)),
                ('sticklingar', models.CharField(max_length=255)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.art')),
                ('insamlingsperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.insamlingsperson')),
                ('odlingsmaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.odlingsmaterial')),
                ('ursprungskalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.ursprungskalla')),
                ('ursprungsplanta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.planta')),
            ],
        ),
        migrations.CreateModel(
            name='bild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500)),
                ('pvnlink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.planta')),
            ],
        ),
    ]
