# Generated by Django 4.2.2 on 2023-09-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bild',
            name='link',
            field=models.ImageField(upload_to=''),
        ),
    ]
