# Generated by Django 4.2.2 on 2023-07-13 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pvn', models.IntegerField()),
                ('namn', models.CharField(max_length=255)),
                ('latin', models.CharField(max_length=255)),
                ('info', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='bilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proviensnr', models.CharField(max_length=6)),
                ('link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='insamlingsdatum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instans', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='insamlingsperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_namn', models.CharField(max_length=255)),
                ('tele', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='lan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pvn', models.CharField(max_length=2)),
                ('lan', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='odlingsmaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ursprungskalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plats', models.CharField(max_length=255)),
                ('info', models.CharField(max_length=255)),
                ('koord', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='mainTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pvn', models.CharField(max_length=6)),
                ('diskriminator', models.IntegerField()),
                ('ursprungsplanta', models.CharField(max_length=255)),
                ('rotade', models.CharField(max_length=255)),
                ('sticklingar', models.CharField(max_length=255)),
                ('planterad', models.BooleanField()),
                ('antal_plockade', models.IntegerField()),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.art')),
                ('insamlingsdatum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.insamlingsdatum')),
                ('insamlingsperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.insamlingsperson')),
                ('lan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.lan')),
                ('odlingsmaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.odlingsmaterial')),
                ('ursprungskalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.ursprungskalla')),
            ],
        ),
    ]
