# Generated by Django 4.2.2 on 2023-08-20 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insamlingsperson',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='planta',
            name='antal_plockade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planta',
            name='planterad',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ursprungskalla',
            name='koord_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ursprungskalla',
            name='koord_lon',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='insamlingsperson',
            name='tel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='planta',
            name='insamlingsperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trees.insamlingsperson'),
        ),
        migrations.AlterField(
            model_name='planta',
            name='rotade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='planta',
            name='sticklingar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='planta',
            name='ursprungsplanta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trees.planta'),
        ),
        migrations.AlterField(
            model_name='ursprungskalla',
            name='lan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trees.lan'),
        ),
    ]
