# Generated by Django 4.2.2 on 2023-07-20 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_art_bilder_insamlingsdatum_insamlingsperson_lan_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TreeType',
        ),
        migrations.RemoveField(
            model_name='art',
            name='pvn',
        ),
        migrations.RemoveField(
            model_name='insamlingsperson',
            name='email',
        ),
        migrations.RemoveField(
            model_name='maintable',
            name='antal_plockade',
        ),
        migrations.RemoveField(
            model_name='maintable',
            name='planterad',
        ),
        migrations.RemoveField(
            model_name='ursprungskalla',
            name='koord',
        ),
    ]
