# Generated by Django 4.2.2 on 2023-08-20 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_insamlingsperson_email_planta_antal_plockade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insamlingsperson',
            old_name='alias_namn',
            new_name='alias',
        ),
    ]
