# Generated by Django 4.2.2 on 2023-08-04 20:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0003_delete_treetype_remove_art_pvn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='landskap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pvn', models.CharField(max_length=2, null=True)),
                ('landskap', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='maintable',
            name='landskap',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='trees.landskap'),
            preserve_default=False,
        ),
    ]
