# Generated by Django 4.2.2 on 2023-09-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0005_alter_bild_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bild',
            name='img',
            field=models.ImageField(upload_to='webdev/trees/static/img_trees'),
        ),
    ]
