# Generated by Django 4.2.2 on 2023-09-24 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_alter_bild_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bild',
            old_name='link',
            new_name='img',
        ),
    ]
