# Generated by Django 4.2.2 on 2023-10-10 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0007_bild_namn'),
    ]

    operations = [
        migrations.AddField(
            model_name='bild',
            name='artlink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trees.art'),
        ),
        migrations.AlterField(
            model_name='bild',
            name='img',
            field=models.ImageField(upload_to='trees/static/img_trees'),
        ),
    ]
