# Generated by Django 4.2.2 on 2023-10-18 12:25

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0008_bild_artlink_alter_bild_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bild',
            name='img',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:\\\\Users\\\\marti\\\\Desktop\\\\Django\\\\trees_db Project\\\\media\\\\/img_trees/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='bild',
            name='pvnlink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trees.planta'),
        ),
    ]
