# Generated by Django 4.2.2 on 2023-10-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0010_alter_bild_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bild',
            name='img',
            field=models.ImageField(upload_to='img_trees/'),
        ),
    ]
