# Generated by Django 4.2.2 on 2023-09-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0006_alter_bild_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='bild',
            name='namn',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
